### ISSUE TITLE
armv7 builds show infinite loading

### ISSUE THREAD

**Issue by adamvas1** [johnstef99/kSMS#1]
armeabi-v7 builds show loading icon forever.
Tested it on three different phones and the same happens.
see [here](https://imgur.com/a/cTdGUcG)

arm64-v8 works fine on other phones.

**Comment by johnstef99** [comment]
I am using the armv7 build without any problem, please check that you allowed SMS permissions!
![Screenshot_20210403-144601_Permission_controller](https://user-images.githubusercontent.com/20647774/113477576-7f2db900-948b-11eb-90b5-3d5009aef0da.png)

**Comment by adamvas1** [comment]
Yes of course I have given the contacts permissions.
Now I found an Armv8 phone on which it has the same behavior.
I assume it may have something to do with google play services, since most of the phones I tried on do not have them.
Is there any way for me to provide logs?

**Comment by johnstef99** [comment]
I don't have google play services on my device.. The app doesn't need play services to work.
You can debug the problem by compiling and running the app in debug mode (you will need flutter).
What version of android are u on?

**Comment by adamvas1** [comment]
Now I have access to an armv7 with android version 5 and an armv8 with android version 10. I can install flutter, it shouldn't be difficult, right? Can the building be done in flutter or do I need Android studio too?

**Comment by johnstef99** [comment]
Just follow this guide https://flutter.dev/docs/get-started/install
Yes you will need Android studio.
